### ISSUE TITLE
[UI] Double title-bar on Audacity and more

### ISSUE THREAD

**Issue by elSolus** [elementary/os-patches#184] opened 2021-07-24 04:04 UTC
## What Happened

Hi. (I'm sorry, new here, don't know if it is the right place to post it)
I downloaded Audacity 3 from AppCenter (now it doesn't show the source but it must be flatpak. There are two Audacities now in AppCenter)

Well, the title and screenshots say a lot.
![Audacity fault1](https://user-images.githubusercontent.com/77105020/126856645-bf252e1d-1ad9-4f2d-9b25-988ad04763be.png)

AND, this one doesn't show the other half of the "noise removal" window either:
![Audacity fault2](https://user-images.githubusercontent.com/77105020/126856660-1444fe97-095b-457f-b3d4-788e76ef5d05.png)

I know not all apps are curated but just wanted to let you know.

The other Audacity (v2.x) works fine:
![Audacity ok1](https://user-images.githubusercontent.com/77105020/126856678-d88c27eb-a431-4693-8721-0c730c3acceb.png)
![Audacity ok2](https://user-images.githubusercontent.com/77105020/126856681-910ec34d-1c0b-429b-b328-6fadb3e1094e.png)

## Expected Behavior

Only one title-bar (not two) and fully visible "noise removal"

## Steps to Reproduce

1. Download Audacity 3 (flatpak)
2. Open the same (and after loading a trak, open the noise removal window)
3. There you go.

**Comment by ryonakano** [comment] 2021-07-24 04:22
Seems like you're using Audacity 3 on elementary OS Hera. Actually, it's already fixed in the next major version of elementary OS 6 which is in development:

![Screenshot from 2021-07-24 13-19-02](https://user-images.githubusercontent.com/26003928/126857104-db077fc8-37c4-490c-83c5-c259fa2cce17.png)

Sorry for convenience, but please be patient for a little before the final release of elementary OS 6 :)

Closing as a duplicate of elementary/gala#244

**Closed by ryonakano** 2021-07-24 04:22 UTC

**Comment by elSolus** [comment] 2021-07-24 07:41
Thanks, ryonakano. Any estimate on the Odin release? (Any at all)

**Comment by ryonakano** [comment] 2021-07-24 07:52
When it's ready™―we often don't set a release date for major releases. However Odin is now in Beta 2 so it should not be that far.
