### ISSUE TITLE
Elementary OS Juno missing icons

### ISSUE THREAD

**Issue by YALTATR** [elementary/os-patches#47] opened 2018-12-13 19:46 UTC
After install Juno with Turkish language, some icons are missing. It's caused by wrong translation. If this situation is resolved by publishing a fix, we will be very pleased as all Turkish users.

![y6p9zy-1000](https://user-images.githubusercontent.com/17274040/49964197-f04baa00-ff2a-11e8-83a4-d8bc3c3a2cfd.png)
![pbggg0](https://user-images.githubusercontent.com/17274040/49964218-fd689900-ff2a-11e8-8b09-5a2c1c4e40fd.png)
![k9kxkw](https://user-images.githubusercontent.com/17274040/49964226-00fc2000-ff2b-11e8-9845-735c25acd93a.png)

**Comment by peteruithoven** [comment] 2018-12-13 19:50
I'm getting 403 Forbidden on those images. You can upload images to github.

**Comment by inzar98** [comment] 2019-02-25 11:20
Is that still exist?

**Comment by danrabbit** [comment] 2019-02-25 23:38
@inzar98 This will need to be addressed in each app and can't be addressed from a single repo. To help track where this issue is occurring, can you file issues against each of the apps where it can be reproduced?

Closing this issue as "Out of Scope" since it can't be fixed within the scope of this repo

**Closed by danrabbit** 2019-02-25 23:38 UTC
